name: releve-urgences-v2

on:
  workflow_dispatch:
  schedule:
    # Heures UTC. En heure avancée de Montréal (été), cela couvre :
    # 00h-03h, 08h-10h, 16h-18h environ.
    - cron: '15 4,5,6,12,13,14,20,21,22 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python src/indexsante_to_sheets_v2.py